
repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.30 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: terragrunt-hcl-fmt
    - id: tofu-fmt
    - id: tofu-validate
    - id: tflint
    - id: shellcheck
    - id: gofmt
    - id: golint
