[thothcf]
version = "1.0.0"
project_id = "terragrunt_project_scaffold"

[template_input_parameters.project_name]
template_value = "test-wrapper"
condition = "08[a-zA-Z]+x08"
description = "Project Name"

[template_input_parameters.deployment_region]
template_value = "us-east-2"
condition = "^[a-z]{2}-[a-z]{4,10}-\\\\d$"
description = "Aws Region"

[template_input_parameters.backend_bucket]
template_value = "test-wrapper-tfstate"
condition = "^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$"
description = "Backend Bucket for tfstate"

[template_input_parameters.backend_region]
template_value = "us-east-2"
condition = "^[a-z]{2}-[a-z]{4,10}-\\\\d$"
description = "Backend Aws Region"

[template_input_parameters.owner]
template_value = "thothctl"
condition = "08[a-zA-Z]+x08"
description = "Team or role owner for this deployment"

[template_input_parameters.client]
template_value = "thothctl"
condition = "08[a-zA-Z]+x08"
description = "Client or Area for this deployment"

[template_input_parameters.backend_dynamodb]
template_value = "db-terraform-lock"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Dynamodb for lock state"

[template_input_parameters.environment]
template_value = "dev"
condition = "(dev|qa|stg|test|prod)"
description = "The environment or workspace name for initial setup. Environment allowed values (dev|qa|stg|test|prod)"

[template_input_parameters.cloud_provider]
template_value = "aws"
condition = "(aws|azure|oci|gcp)"
description = "The environment or workspace name for initial setup. Environment allowed values (aws|azure|oci|gcp)"

[template_input_parameters.deployment_profile]
template_value = "default"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Deployment profile aws cli"

[template_input_parameters.backend_profile]
template_value = "default"
condition = "^[a-zA-Z0-9_.-]{3,255}$"
description = "Backend profile for s3 remote state"
